### ISSUE TITLE
GPL v2?

### ISSUE THREAD

**Issue by GwenNelson** [m1m1x/memdlopen#1]
Hi

This looks like a perfect library for a game engine project i'm working on, but I sadly can not make use of code under GPLv2 - would it be possible for you to license this code under GPLv2, possibly with an "or later" clause?

It'd be most appreciated

**Comment by m1m1x** [comment]
Hi,

Sorry for the delay.
What kind of license would suit you? I'm not really sure to understand if GPLv2 is fine for you or not.

**Comment by GwenNelson** [comment]
Since I sent that, i've hacked together a cache system (write the lib to a
disk cache, dlopen() it) that's probably more cross platform anyway so i've
no longer got a need for your code.

Thanks for the response anyway, GPLv2 is what i'm using (and what a lot of
code out there uses). I'd suggest making your license "GPLv2 or later" or
one of the BSD or MIT licenses if you want to encourage usage.

Cheers

---

“Lanie, I’m going to print more printers. Lots more printers. One for
everyone. That’s worth going to jail for. That’s worth anything.” -
Printcrime by Cory Doctrow

Please avoid sending me Word or PowerPoint attachments.
See http://www.gnu.org/philosophy/no-word-attachments.html
